import { defineConfig } from "@playwright/test";

// Generated by Dyad. The dev server is started separately by Dyad's
// preview, so we point baseURL at the already-running proxy URL (passed via
// env) rather than using Playwright's `webServer` (which would double-start
// the app).
// // Uses your installed Microsoft Edge (no extra browser download).
export default defineConfig({
  testDir: "./tests",
  // Run serially against the single dev server.
  workers: 1,
  fullyParallel: false,
  reporter: [["json", { outputFile: "test-results/results.json" }]],
  use: {
    baseURL: process.env.DYAD_TEST_BASE_URL || "http://localhost:32100",
    channel: "msedge",
    screenshot: "only-on-failure",
    trace: "retain-on-failure",
  },
});
