// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vtwlcaikxfnhngisgfgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0d2xjYWlreGZuaG5naXNnZmd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0ODU3MjMsImV4cCI6MjA3MTA2MTcyM30.1ltDW9yIuOjvd7qLGHlGZAlFlPGh3sGK8-o-jaogJmg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    // Adiciona o cabeçalho 'x-client-info' com modo 'no-cors' para mitigar erros de CORS
    headers: {
      'x-client-info': 'supabase-js/2.75.1 (no-cors)',
    },
  },
});